name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Укажите нужную версию .NET

      - name: Restore dependencies
        run: dotnet restore /AST/AST/AST.csproj

      - name: Build
        run: dotnet build /Test/Test/Test.csproj--configuration Release

      - name: Run tests
        run: dotnet test  /Test/Test/Test.csproj --configuration Release --no-build --verbosity normal

      - name: Publish
        run: dotnet publish --configuration Release --output ./output